const TOTAL_LETTERS = 28;
const START_DATE = new Date('2026-05-10');

const _KEY_SEED = 'rwire';
const LETTERS_DATA = {
  1: "Nx4AXkU8eHpjEABfBBIHBxFQUgQcUjdUFlc+GxdUXHpjf294HFcYBwBCBhZJAgRWGxkIUhFDHQEMAARYUkVRUglUBgMMAAARWgIHE0VQHlcOGwpDHBhFUo0RGxkcBgxdF1cZAApHEwUMUgQRARUFHQZSEwUFF0VBAB4EE0wff31keCtUHhtOEwlFABZJAgRWGxkIUhVEHR5JEQRDGxQIAAARBxkIUgNeBhhJEwkRFR4GAAteUgQMUgtUUh8IG0VHHRAFGwQRF1caAgBDHVcKG0VQGwIdG0VQUgQMHBFYABJJBwsRAhhOUghUHBhJHgQRFh4aBgRfCBZJEQ1UUgcMAQQRFR6JUhFQHAMAARZYHxhHf288eDUcHQsRFh4fFxdFGxoMHBFeUh4HUjZBExAHE0s8eHpjJgwRExoGXkVjGxQKExdVHQ==",
  2: "PxZJEQxTHRgGXmg4f30aBgREHVcZFwtBExkNHUVTUgYcEwtWHVcEG0VaEx5JFgBGBhhJEQ1XUhgOHAwSHxYdBgxcE1cdG0VBBBIOHgwSAhIHAQRcFhgEG0kSF1cGFQtbUgQMAAQSBh5JEwFWHQUEFwtGG1cZFwtBExkNHQhbXHpjf29kHRAFGwoSER8MUhFHUgQIAhVbE1cKGgASExkKGkJbHVtJHQJcG1cKEx9IHVcNG0VVGxgbHAoSWhJJAgBcARhJEQ1XUhYNFxZBHVcKGgASARIAUgldHAMIHAQSAR4IUgRcERgbE0VCFxAOGwoSGhYBEw1TW1lkeGg4PBgHUg1dUhoGHhFXUhYFBhdXUhQGAQASFhZJEwJVGwIHFQBAF1cZFxcSHRAOG0sSIQcMAAoSER8MUhVTAQQAUgoSExULGwQSAhYaAQRGHVccHEVQFxtJAQBRHRkNHUVVGxgbHAocf31keDFbUhYEHUkSIB4KEQRAFhg=",
  3: "OhgFE0UbHBIFUgZSARhJHApdUgQIAgBAAR5JAgzKUhQGAQQTAR4OHAxVGxQIUgZaExhAXmg5f30KVY0TBxkIUgZcARZJEQ1WUhoAUg1SG1cNFxFHHVcKGgATGhhJHwBAARhJBhdSUh5JHwBAARYOFQwTARYFBARHG1lJOgRaUgQKAAxHBhhJUAtcHFcaHUVXEwEfFxdcUhQGAUJbHVcPExFHHVcZFxcTHxIbGxFSABoAUhFWXFVkeGg5JBgOHgxcUhQBF0VHB1cbGwlWFRAIUhRGFxsFE0VVABYaF0VWUhsIUhdaEBYFBokdUicMAAZbm1cAHUVdHRlJAQoTERgaVQ1cUhEIBhFcUgcMAEVeFwUABgRBHx5JBgAdUj4FUghcFhhJGwsTEQIAUhFBEwMdG0VfF1cZFxdAHRkMUgRDAhIHE0VfF1cKHQtcARQAXEV6HlcEHQFcUh4HUgZGG1caBgRFG1cKHQsTPgIHE0sTOxtJFARHBhhJEQ1WUgMAUgZcAAUMFQJaUgQMHxVBF1cYBwRdFhhJFgxQG1dLEwtQGlAAHUcTF1cIFQJaBxkOG0VaHldLBgwTExoGUEkTAhIbEQ3aUgcMAEVHF1cYBwBfHhZJO0VQHRkdE0s+eHpjMQpdBhZJEwtQGhJJAgBBUhoMXkVFFwUIHwBdBhJJBgRdBh4aAQxeHVlkeGg5Jh5JEwhcXlc7GwZQEwUNHQ==",
  4: "PxZJEQxVHVcIHwpGF1tkeGg+Hx5JHwRaERZJPwBYBh4HE0s5eHpjPwwUHxYHEQQUAwIIHAFbUhQAUhZdExoGUhZRFgIdG0VHBxsFE0VEExkKGgxaE1cIUgNBHxYbF0VRUhQIHBFVABJJFhdVAQNFUgZbHFcFE0VABxZJEQ1dBhYbAAQYUhQGHEVABwMdHUVdHlcaGwlRHA0AHUVQG1cYBwBYUgcGARFbUhQBF0VbABoIG0XcUhMABABaBhYdHUVBHFcZHUIUBxkIUhVVAAMMUgFdUhoMXEV6HRlJAQoUAQcAFwJVABJJAgBGER+AUhBaHVcaAgpAUhMMHkVTFxkMAAAUFh4fFwtAG1caAgBXGxYFF0kUFBgbAQAUmlcAHkVEHQQdHUkUFBgbAQAUARIAUhFBUl8EE0VEFxkaHUVYE1caFwZbHBMIW0s5eHpjMQpZBxkYBwAaUiQZFxdbUhQBF0VdHFc6AgRTHBZJBhAUExULGwQUBgUGBARAHVcAHkVABxhJAgpHBhhJFxRBGwEIHgBaBhJHUjBaUgcGARFbUhMGBAAUAQMIAAAUARIHCAQUFhgfFxcUFBYbF0VaGxIHBgAUFh5JAgRGBh4KHQlVABJFUgZcF1cdG0VSE1caBgRGF1cLFwtRXHpjf29gG1cIHwoYUiUAEQZVABMG",
  5: "MxoGAAAVHx4GXmg/f30YBwBGBhJJHgBBBhIbF0VQABYHHUVSG5dJAQZHGwMdF0VEBxYHFgoVBh5JGgoVFhYdHUVcHlcbFwJUHhhFUghUUgQGHAoVAR4KBxdaUhQBF0VaFRAAUghcUhoIHAZdG1cdEwtBGwQaGwhaXHpjf29mEQIaE0VGF1caHQtaUgIHUhVaVVcaGwtBFwMAEQ1QXlcIBBdQG1cIEAdUAQMIHB9UUgcIAApZF1cNE0VGEQUABABHF1ccHEVZGxUbHUkVHxZJmkVSG5dJGwkVRVckEwJSGxhJF0VcHlcdFwhFHVcaBhdcHBAMUg1UGhYBE0s4eHpjJgwVExoGXkVnGxQKExdRHQ==",
  6: "MR4IHUVCEwMIXmg8f30GFQJfUp9JBABYFwUNnkVFF1cHHQsWGhhJFARCBhhJHwRaF1cAUgZXHhQGHgwaUgQdE0VfHB4TGwRYFhhJGwkWHBgaBhdZUgcbGwhZUhEAHAAWARIdBgxbExkIUglZHAMIHAwaUhkGHEVGHQMbkkVbEx5JFxZFFwUMUgFfBBIbBgBYBhJJEQpbF1cYBwBaHh5JEQpYUgMMUghXUhEIAJcWAR4KBxdXHxIHBgAWAwIIHgZeF1caFxdXBhZJERdXCA5Hf287eDMABABEBh4dG0VTUhEcHwQWBhYHBgQWBhYHBgQWFwULE0UeER8MUhVXHhIaFwhTHAMMUo0WHxIOHgxZUhMMHkVQBxoGW0s7eHpjJgwWExoGXkVkGxQKExdSHQ==",
  7: "Nx4AG0k6eHpjBwtWUgQMBhFeHxYHE0s6eHpjMQpaF1caBgReTVcqHQgQmlcFE0VRExoAFQleE1cGARVeBhYHBgAIUjQGH0LfUh4FUgZeEBhWUi1WG1cdAApBEwMGUhRCExsKBwtYUhQGHEVUBx5JAgRFHhYbF1oXIQMIG0VVFxkMTWg9f306HUVUGhJJHApZUgccHQwXAB4aAgpZFhIbHwwXAwIAXEV6E1cdF0VbHVcKGgxSFhhJHgoXAQMMARZYXlcZFxdUGp5JBApQHh4GUgZfF1cdB0VEEwcZGwQXER8MUgZeUgcMHBZYXHpjf29kAhIbHUVUGhJJBhAXHx5JARFeE1cbGwBaAh4MHAFYUhMAUgRCFh4GUglCHBABG0VYABJJEQpZUgMcBhFeUh5JAgxUERgFG0VTFwMdEwJbG1lkeGg9Jh5JEwhYXlc7GwZUEwUNHQ==",
  8: "MxoGAAAUf31keCRWER8MUgpfFR5JHwwYHxYHEQ1RUhQGHwAYHlAIAAxZXlcaAgBKHVcKGgAYBgJJBgwYAQMAE0VcGwEMABFdHBMGUgAYAQMAE0VeExQMHAFXUhsIUgdXGhIIHwxZHHpjf29sG1cIHwoUUiUAEQZZABMG",
  9: "MxoGAAAZHx4GXmgzf30BEwwZERYEEAxYBhhJGwkZARIHAQoZFhIFUlELQllkeGgzIgUAHwQZFwUIUhBXUhkcHwBLHVcKHQsZBxlJAQxeHB4PGwZYBhhJHwpVBhhJEABVHhhHUiRdFwQaHUVUG1cbGwZWABMIUgRXER8MUgFQUgMMUgAZHx5JFAQVUgYcGwtdG1tJAgBXARYbF0VYHhsMUgFMF1cKHRZcUhQBF0VJG45JEwhWUhYFUghWHBMGUgAZAwIMARFWUhkGHEVaExoLGwBLklcZG5wXf31keDFQUhYEHUkZIB4KEQRLFhg=",
  10: "MR4IHQodPXh6Yx0CVllSAQYVCVhfUhQBF0VFRVIECAIVWFFSFAEXRV9fHFcbGwBCUx1XCBZFUEMRGAUGBENVUgIHE0VSURwNBhwAEVQbVw0ABEJEUgQMHB9QEAISBwEEQ0QbW0kUCkNDF1cZFxcRQQcSGgYKEV0bVxkbBFJVUhQGAYkRRBMZHR1LPDp/fT0bRVBdHVtJIAxSUxMFDR0=",
  11: "MR4IHUVQXB0FDF5oOzx4BB0TDBFSExkdEwtVXlIeB1I2QVAVGQhNaDs8eCQZFxdeERYeSQGJHxE8GAdSDFxBHQUdE0VVXgQSU1IWXkUGGEkeBBFVHRQKGwQdERsZSREEXFQAFkVSFVRDUgQdAARVUFIUBhxFXVRSFBwUA1hUXFc6AgBDXlIUARdFRURSBB0bBBFSExkdEwtVXlx6Y39vchaaVxgHBF1SHQQIUgxfEQYSSQMQUF8WGEkUBFgRHhJJEQpCVFIUARdFUFwbVwoaABFfHRlJAQwRQgIeDBUEHxEhHkkEAFVUUhJJEARCRRNZZHhoO2UbVwgfCh0RIB4KEQRDVR0=",
  12: "MR4IHUVFUwYWRX9vPDgdEA4bRVdTERQAHUVYXlIlABEGUEAWGEkBAENbHVcZFxcRBkJXGhcGXlwWHklaBkNdHBgEFxFDU1IHHAAAGBx/fWR4NERTHBMGUghYEhoWAFIBVEYGGEkDEFReHhZJEQpCU1IUARdFRVtSBwwBBEdTXlcFVQ1QW1IRCAYRXhIRGAdSEF9TUhMMHgxSUwYSEwgEEVEaEkkfDBFaE1cPExFFXVIEChsKVl4bEhsXSxF3UgcGG0VFW1IEDBtFQUcAEkkBBkRBEwMIXEV8U1IECgcWUEAGHkkCAEMSFh4bF0VSXR8SSQERUFtSn0kbCV1XFRYFF0kRVh0BGxcHU1dSEhoBAENRG1ccHAQRXwcbHRNLPDh/fS0bF1QSAwIMHgleEhEfDFIVQ10EHkmaRURcE1cNFwldV1IUBgEAEUIbjkkQAF1eF1cKGgARWhMeR1IrXlxSAwYVCVhXABsIUghQW15XBxcIXFccGEkCAEMSARUIFQlYXVx6Y39vZVtSFgQdSRFgGxQKExdVXQ==",
  13: "Nx4AUgRcXAASRX9vPDkBHggfChFCBxYaG0VQEx8SHZJLPDl/fScdCxFAHVcaF0VeVBUeSRsLEWACFg4cBBFQVZ9JAQpdVl5XHxcLRVxSGEkTFV5QExsAARZUH1IaCFIWXhMRHwxSAVATAwIIHgZZVlIHCAARVBMRHkkBAFgTBgJJEQ1UEx4SDhUMEUIHEhoGABFBGxABF0VUExsYSRUM0RMBGBsADFVcUhQGHwARRhxXCgAARVocGEd/bzw5PxYHEQQRUhwUBgAEEUYcVxkXH0tWBgMGXkVC31xXORcXwxMdBQQTDBFAGxYEHUVfVh5XGxcRRVoeHgcXCh0THBgHUgheXx4eCB8KEVIWEhoBChFbEx8IGgQfPnh6YyYMEVIfGEVSN1hQERYbFgo=",
  14: "PxZJEQxQWx0YRX9vPD4fEh2SRUJAABYNE0VEUhQeChsEXVFSBAAVC15GF1cMUhZYUxwYGxtLPD5/fSQ7RXx1PDQhO0VyeyE+SSYkf2A9VyozP2t7XHpjf29iURtXDRcLRUYdVwYVC1gUAhITCAoRUBcbBRNFXF0TVw4bCkNaEwMIXEV0FBwYRVILXlpSn0kCAEJVHAMMSEXZFB4WSQIEQ0AXVwQbAl1dHQUMXGg7OXgjAFIEXFteVzsbBlJVABMG",
  15: "MR4IHUVQWB0FDF5oOzh4JBkXF14VBgJJBgwRRgYeCFIBWEMXBR0XC1VaXlcEEwJQRxtXGgYEWBUeEg4VAF9RHVcYBwBCQRNXBRcRRVAAFkkUEEJUUh4HUhREVB4UARdFQkUdA0kQAF1ZGwQaGwheFVoEDFIGXkaeVw8dFkJQUhQIAAxSVFIbCFIDXkEdVwQbRUNUERQGHwRfUR1XARMNUF0TXkd/bzw/Jh5JAgBfRh1XBhULWBUVHgYAC14VEwcZFwtQFQEUCAYRUFsdVwUXRQUHQltJHQJfXFIZBgYRVBUDAggcAV4VHx5JARNUUh4eBlIAEVsdGUkBAFgVExQKEwtFWlIWSR8AEVBSGA4cDBFDHRsdE0VSXRdXDRcTXhUUFhsfDBFZE1cEGxZFVFITCFIWXlkdWWR4aDt7HRlJBABVWlIbTh0XUBUWHkkADFJaHx4HEQxQRxdXCFIVUEYBFhsXRUVABgMMUhREUAEDDFIGXkYXVwodCxFBF1lkeGg7YRtXCB8KHRUgHgoRBENRHQ==",
  16: "MxoGAAARWxsYRX9vPDwGHkkCAF9FHVcYBwRfUh1XGRMXRVNSAgcTRVJXHA0GHAARU1IeBVIVQ18fGEkbFkVfHAMGUo0LFlAYAlIURFMBAwhSCVAWFhIfHUVcVxwTCAAAEUUHFQAGChFXUjIEGwlIFFx6Y39vZV9SBwwcFl4WExkKGgARRwcWBxYKEUYTBQUdRVJZHFcYBwRdVQcZBlIAEVIXAQZSF1hGFwMMAAARWhdXCh0WVBZDQEkECl1CF1tJAgBDVRqeSREKXxYGEkkcCl8WAQIKEQBVUwQWU1IGUEYbBAobRUJTHwcbF0VFQwYDBlIEXRYEGAUdSRFTUgcGG0VHWR4SHxtFQUMAEkkbCRFaGwEMHgleFhAYBwcWEVIbVxoCDFRREw0AHQtUFhoWARMNUBh/fWR4LF8WAgUIBgxSV1IDAFIVVFgBGEkBAFxGABJHUjZUWAgWSRMCVFgWFkVSFlRYCBZJAhdeWxcaBgAMUBpSFhwGClxXBh4KHUs8PH99PRtFUFsdW0kgDFJVEwUNHQ==",
  17: "MR4IHUVFVgYWRX9vPD0fHkmaRUVYABkIBgQRXhxXHRcWRVZSBhwXCV1WUgMcE0VFUh0FABNfERU+AgcTRUdSFhJJEQpCUlIUARdFX1gbVxwfBF9eUgQKFwhYFxwYB1ITVFMbFgQdRx86eHpjIgzIFxEeSQIAX0QdVwxSFVjOUhoAUhZQFxEfDFIER1IEHkkABFZeHRkMUhFEF1oEHQAEX1heVwwaWhFfEx8IGgQYGVI6CBUEQ15SGwwbRVBBFwEIUgZQRxsDBlIRREMGGEkCF1haE1cNG0VfWBtXDFIGWBcVAggAAVBBE1cZFwtCVhwTBlJHXFZSBhwXFkVeUgYcEwtVWFIEAFIWR1IVGwATC14IUFlkeGg7eR0ZSQQAVVhSG04dF1AXFh5JAAxHUhYSGwQMEV4cBAAXCFQZf31keDFYFxMaBl5FY14RFAgAAV4=",
  18: "Nx4AG0k8Mn99GRsGUlceGEkfAEJLExAOGwoRShMHABYKEVUTVwAfFV5KBhYHBgAfNXh6Yz0CX1FSEAAdF19XUgQMHB9QGBYeSQYAEVUbVwodC1ddABoIUglQGAEDDAEWUBgRGBoTXxFLFx5JFgxHXRwDCAYEEVsTBAhcRX9XHFcHFwkRSxcZGh1FQlwdGwobC1BMHVcNE0VTWREeBlIVVEoHEAAcBB0YAgUGAhdYV1IZDB5FQl0cBAZSFUNZBh4KHV8RWx0ZSQYAEVUbVxoXC0VXUhkMHkVBVwEDBlICWE0BAwZcaDs1eCYcGwtVUVIEhV5FXFFSGggcBllRUhMIUgxcSBMNExsXVBRSGghSBF1VFxkGUhZeGBEYB1IGVEoGEhMIBBFcHQEMUhNeXx4eBlIRXkocFhsXSzwyf309G0VQVR1bSSAMUlsTBQ0d",
  19: "MxoGAAAdNHh6Y19UARdSJIVeRVlWUhEIBhFeGQIFBgIXWFZSHgVSBl5MHAMNHRJfGQEDBlIMXEkTDRMXC1VWXHpjf29wXRcEGh1F2RkEHgobC14ZAQIFUhZUSxsYR1ItXhkVHolSEF9YUhsAARFQGR8SBwYEXVxSFhoBEENdE01JAgpCTRtXDR0TVBkCGBsGBENNG1tJEQpCXFITCFIDUEsXW0kRCkJcUhMIUgFYSwYeSRUQUEsWFgcWCkVQUhkMFQlYGR0UChoMEUkXBQoajBFQHFcKGgRFGQESBBAXUFcdVxoXCEFLF1cZG5wRSRsUCh0JVBd/fWR4KFRVBh4HE0VSHppZST4EEVoaHh0TF0NYUgccAAAfGTsYSR0TR1ATGgwcEVQZAgIbF0kRSAceSRMBEVgBBwwGEVBLBh5Hf288MyYeSRMIXhVSJQARBlBLFhg=",
  20: "MR4IHUVTXR0FDF5oOD14GA4VDBJWABYaF0VBXRsSBRMRUxAWEgVSAltfABkGUk1fUVIaDAAMRlEGFkBIRUFfHBhJFABeWREeGgEMX19SFAEXRUZFUhIaGxZGUVx6Y39vfF8cVxodCV0QUBkMHglTEB8eCFITW0QTVUVSFUBfAgUAHUVbXlIQDBwAQFEeEkkcAF4QAh4IHABGUVIjDAAXUxxSFAYcRVtcUgMcHUVfXxYYSRYMElUBBAwAAB4QHhJJBhBXEAIWGgEMXV4bW0keBBJEBxZJAQBcQxsVAB4MRtBSEkkTC1FYF1cFF0VGRRdXDxMGUVVSBAoXCFcQGhYBEw1THn99ZHitEkITBQZSFV1EFwVJFgxAVVICBxNFUV8BFkkRCkHcUgQMHB9TEAERBgAfXR5SNAYcRUZVUhoAUhNbVRwSSRMQRl8fFh0bBl0ef31keDFbEBMaBl5FYFkRFAgAAV0=",
  21: "Nx4AXmg4PHgCBxNFQVQGAwAfBFxQUgMGHAFTEQYYBxYEHDx4emMhAEZFF1cOGwpAXxtXDFIDW18TGwQXC0ZUUhkAFwtGVFIEChoAQFwdVwAcRV9UCA0GXkVcWBcZHRdFXlAVW0kcDFdfBhJJEQpcRQAYBR4EQFRSGA4cDBJWGxgbHAoSQhdXAB5FQVQAAQwARdoRHRlHUjZdXR1XHQdFRFQAFkVSAVNdUgEABAoeEQQeChsLUx9/fWR4K11fUgEMFgoSXVUYGxNFVlhSAQwWAEBFG1cdExFTH399ZHgxWxETGgZeRWBYERQIAAFd",
  22: "MR4IHUVGUwYWRX9vPzgfHkmaRUBbHxYaBgQSWxxXHRcWRlNSBhwXCV5TUgMcE0VUQBMEDEhFEEYbVwgfChJXARYdBgRfVxwDDFIGXV8XVxoXDBwQf31keK0SRxwWSRYMEkMHEgUeABJUABYaG0VRWhdXGhcIUEATGQZSFVtRERgFF0VXEhsZHxcGVxIGHkkADFBTHgMIHAoSVhcZHQAKHBI8GAdSR0NHEwQAUEkSXB0ZSVAEEkYAFh0GDBAeUhkGHEUQQwcWBxYKElQTHkkDEFdBBhhLXEV3QRMDHRMIV1wGEkd/bz84MxkKGkJbXVIUBgGJHhIbEwwcEVtRHU1JBgwSUx8YSRcWU0YGFgQXC0ZXUhQGHwASQRceR39vPzgmHkkTCF0eUiUAEQZTQBYY",
  23: "MxoGAAASXhsYRX9vPzmaVw4bEFVdHRgGHUs/OX99IB5FX1YBEkkbCxJQBx5JBgpAXRtbSQMQW10WHkkbCRJDG45JEABeXx1XDRcJXhQTGQcdSz85f30qGwtDRhdXDhsKQF0bWUkhEV0TERIbEQRcVx1XDRtFUVwfBwYAEVNBHx5JFgQSQxcFGh0LUxMcGBsfBF5WUhoIUgtdXVIaAFIXW1YBFAxSB1ddGwQaGwhdHX99ZHgxWxMTGgZeRWBaERQIAAFd",
  24: "MR4IHQpdGH99ZHgUR1UGAxsdRVVdHQUHG0s/Pn99JBtF2hQGGBscBEZVUh4HUghXWgYSSQMQV1geFkkBAEBVUhMMHkVGUR4SDx0LXRQfGBsGCggUGxhJGwsSRBMZABEKHhQCGABSEUBbBBhJGwkSVxMBBlIAEkcRBQAEChIWOjhJICxhez4jJlBFX1UcFAZSBERRAQQAUgxcQhcZHRMRXRQbGR0XF1xRBltJmkVBQBMDCFIQXFVSBAwcFlNOGxgHF0VUVRwDCAERW1cTVxkXF1Fcm1caGwJcXRQeChMTUxQRHwxSFV1AFwEGUhZRRhsBDAARWxQTGQodF1Maf31keDVXWgEYSRENVxhSBwgBFlNAG1cYBwBBQBtXBQcLVVwbBBobCFsUAwIIBhFAW1IQAB0XXF1eVwUTRUFRHAQICAxdWhdXDRtFQVseGwAXE10UARYbkkVCXYtXBlIIV1odVwUTRUFAFwQaE0s/Pn99PRtFU1kdW0kgDFFXEwUNHQ==",
  25: "MR4IHUVTWB0FDF5oODh4AxsXRVVcHQUHG0s/P399JhUCWxUcHgwcEVcVFh4aEQpARhtXDBwKQFgbTUkEClVZGxhJAQpeWlITAAARWxURHwxSBl1bUgMMUgRcVhoSSRsJEkYbGwwcH1taUp9JEABeWR1ZSTwKXBURUIFSBFxGGxZJFgwSUR0BDABFQlQAGwgAABJFFwVJFApATxNbSQIKQUYbFgQdRUFBEwUMUgneFRdXCxMWRlRcemN/b/oVBxkIUgZdRhNXGxMXW0YBHgQTSRJQUh4GUghXFR4WSQYAXFIdVxoGF1dBBhZJFApAQRsEGhsIXRt/fWR4MVsVExoGXkVgXBEUCAABXQ==",
  26: "MR4IHUVGVwYWRX9vPzwWGBkdAV1bExkAXGg4O3gzJiIqdnk/Nic7RUZZABkAXEVh2l5XBR1FQVUAHh8dRVNYER8MUgxcFh8WAAcWUVkeGEkCAFxFE1cdB0s/PH99KhtFQVkcGEkHCxVfHBEAHAxG1lITAFIGXUUXVwoaABJAHQUbFwwSUhsFHRtJElsTVwcdCxJFEwWbUghTX1IVGxMTXRYDAggcEV0WBhJJEQpcFh4SSQIEQFkeEmR4aDhyGwEMABFbQhtXGAcAQUIbVxweEVtbG1cOGwpAWBtZSTYKQlkWGAQTC1sWFB4HEwlfUxwDDFIGWxYBEgBcaDg7eCMAUgRfWV5XOxsGUVcAEwY=",
  27: "MR4IHUVTWh0FDF5oODp4EwYfBFxeXHpjf292WB8WBxtFRlgAGQBSABJEHRkGUhZbVAcFBlIGWlJSGQYcRUFDHVcZFwtBVhwTBlIEVhcTGx0AChw6eHpjPApcFxoYSRwMV1kGUAgeEUBYUhMIUgFbRRdXChoAElkdGUkGDBJWEBUAE0VVXpJXGhEXW0MGGEkbCxJGBxIaBgASRBcDHRsIU1kXTUkfDBJEFx5JHwRcVBMDCFIRU1kGHhoBDF9YXlcaHQtdFxQeDAAKElMbVx0XRVZWUh4EAgRITRsFDFIAElkdGUkEAFZYUhtOHRdTFxYeSQAMU1UQBQgRBltWAAMAXGg4OngjAFIEX1heVzsbBlFWABMG",
  28: "MxoGAAASVRsYRX9vPzIHGx0bCFMYHhIdBgBAWVJfBRMGQFEfAgoRDFMYWVcIAhVeWQcEBlIDW1YTGwxbSz8yf306FwwSXxuXSQYKQFYTAwheRUFMEx5JBgpAVhMZDR1FXRgBEgBSDFwYBBgFHUVfXRwDGxdFXl0VEABIRVtWUhgOHAwSWxMEBlIGVxgeUAETDBJeEwMdE0sSbhcZHRsWV0wGEkkVDF1KHB5JHgpcTBMZCF5FW1ZSGgwIH10YE1cZFxdBVxwSSRwQXU4XVwxSDFwYBxkIUglbVhUCCFILXVZSAxwTSxJrFx5JARFTTBNXDx0XRlEBBAAfBBw1eHpjOwoSSx0ZBlIUR1FeVwgcBl1KE1cZG5wSURwZCB8KQFkGGEkWDBJIAB4EE0s/Mn99LxsLVxgWEgUeABJUFwMdFxdXFlI4GxNFUFkBAwhSFVNKHRsMSEVEURcZAFIUR1FcemN/b2ZRUhYEHUkSahsUChMXVlc="
};

function _xor(str, key) {
  let out = '';
  for (let i = 0; i < str.length; i++) {
    out += String.fromCharCode(str.charCodeAt(i) ^ key.charCodeAt(i % key.length));
  }
  return out;
}

function _decode(encoded, n) {
  const key = _KEY_SEED + n;
  try {
    return _xor(atob(encoded), key);
  } catch(e) {
    return null;
  }
}

// Utility to encode a letter — call from browser console
window.encodeLetters = function(text, n) {
  const key = _KEY_SEED + n;
  return btoa(_xor(text, key));
};

function getUnlockDate(n) {
  const d = new Date(START_DATE);
  d.setDate(d.getDate() + (n - 1));
  return d;
}

function isUnlocked(n) {
  const unlock = getUnlockDate(n);
  const today = new Date();
  unlock.setHours(0,0,0,0);
  today.setHours(0,0,0,0);
  return today >= unlock;
}

function fmtDate(d) {
  return d.toLocaleDateString('it-IT', { day: 'numeric', month: 'short' });
}

// ---- Modal ----
function createModal() {
  const overlay = document.createElement('div');
  overlay.id = 'letter-overlay';
  overlay.innerHTML = `
    <div class="letter-modal">
      <button class="modal-close" aria-label="Chiudi">×</button>
      <div class="modal-envelope">
        <div class="envelope-flap"></div>
        <div class="envelope-body">
          <div class="envelope-heart">♥</div>
        </div>
      </div>
      <div class="modal-paper">
        <div class="modal-number"></div>
        <div class="modal-date"></div>
        <div class="modal-text"></div>
      </div>
    </div>
  `;
  document.body.appendChild(overlay);

  overlay.querySelector('.modal-close').addEventListener('click', closeModal);
  overlay.addEventListener('click', function(e) {
    if (e.target === overlay) closeModal();
  });
}

function openModal(n) {
  const overlay = document.getElementById('letter-overlay');
  const encoded = LETTERS_DATA[n];
  const unlockDate = getUnlockDate(n);

  overlay.querySelector('.modal-number').textContent = 'Lettera ' + n;
  overlay.querySelector('.modal-date').textContent = fmtDate(unlockDate);

  if (encoded) {
    const text = _decode(encoded, n);
    overlay.querySelector('.modal-text').textContent = text || '— lettera in arrivo —';
  } else {
    overlay.querySelector('.modal-text').innerHTML = '<em>— lettera in arrivo —</em>';
  }

  overlay.classList.add('visible');
  document.body.style.overflow = 'hidden';
}

function closeModal() {
  document.getElementById('letter-overlay').classList.remove('visible');
  document.body.style.overflow = '';
}

// ---- Init ----
document.addEventListener('DOMContentLoaded', function() {
  createModal();

  let unlockedCount = 0;
  for (let i = 1; i <= TOTAL_LETTERS; i++) {
    const card = document.querySelector(`[data-letter="${i}"]`);
    const dateEl = document.getElementById(`date-${i}`);
    const unlocked = isUnlocked(i);

    dateEl.textContent = fmtDate(getUnlockDate(i));

    if (unlocked) {
      card.classList.add('unlocked');
      card.classList.remove('locked');
      unlockedCount++;
    } else {
      card.classList.add('locked');
      card.classList.remove('unlocked');
    }

    card.addEventListener('click', function() {
      if (this.classList.contains('unlocked')) {
        openModal(parseInt(this.getAttribute('data-letter')));
      } else {
        this.classList.add('shake');
        setTimeout(() => this.classList.remove('shake'), 400);
      }
    });
  }

  document.getElementById('unlockedCount').textContent = unlockedCount;
});

setInterval(function() {
  // refresh states every minute
  let count = 0;
  for (let i = 1; i <= TOTAL_LETTERS; i++) {
    const card = document.querySelector(`[data-letter="${i}"]`);
    if (isUnlocked(i)) {
      card.classList.add('unlocked'); card.classList.remove('locked'); count++;
    } else {
      card.classList.add('locked'); card.classList.remove('unlocked');
    }
  }
  document.getElementById('unlockedCount').textContent = count;
}, 60000);